CREATE TABLE countries (
    countryId SERIAL PRIMARY KEY,
    country VARCHAR(100) NOT NULL,
    region VARCHAR(10) NOT NULL
)

INSERT INTO countries (country, region)
VALUES
('Algeria', 'North'),
('Angola', 'Southern'),
('Benin', 'West'),
('Botswana', 'Southern'),
('Burkina Faso', 'West'),
('Burundi', 'Central'),
('Cabo Verde (Cape Verde)', 'West'),
('Cameroon', 'Central'),
('Central African Republic', 'Central'),
('Chad', 'Central'),
('Comoros', 'East'),
('Congo-Brazzaville (Republic of Congo)', 'Central'),
('Congo-Kinshasa (Democratic Republic of the Congo)', 'Central'),
('Côte d''Ivoire (Ivory Coast)', 'West'),
('Djibouti', 'East'),
('Egypt', 'North'),
('Equatorial Guinea', 'Central'),
('Eritrea', 'East'),
('Eswatini', 'Southern'),
('Ethiopia', 'East'),
('Gabon', 'Central'),
('Ghana', 'West'),
('Guinea', 'West'),
('Guinea-Bissau', 'West'),
('Kenya', 'East'),
('Lesotho', 'Southern'),
('Liberia', 'West'),
('Libya', 'North'),
('Madagascar', 'East'),
('Malawi', 'Southern'),
('Mali', 'West'),
('Mauritania', 'North'),
('Mauritius', 'East'),
('Morocco', 'North'),
('Mozambique', 'Southern'),
('Namibia', 'Southern'),
('Niger', 'West'),
('Nigeria', 'West'),
('Rwanda', 'East'),
('São Tomé and Príncipe', 'Central'),
('Senegal', 'West'),
('Seychelles', 'East'),
('Sierra Leone', 'West'),
('Somalia', 'East'),
('South Africa', 'Southern'),
('South Sudan', 'East'),
('Sudan', 'East'),
('Tanzania', 'East'),
('The Gambia', 'West'),
('Togo', 'West'),
('Tunisia', 'North'),
('Uganda', 'East'),
('Zambia', 'Southern'),
('Zimbabwe', 'Southern');