CREATE TABLE countriesHumanFacts (
    factsListId SERIAL PRIMARY KEY,
    capitalCity VARCHAR(20) NOT NULL,
    largestCity VARCHAR(20),
    populationInMillions FLOAT NOT NULL,
    areaInThousandSquareMiles FLOAT NOT NULL,
    drivingSide VARCHAR(5) NOT NULL,
    languages VARCHAR(100) NOT NULL,
    timeZone VARCHAR(20) NOT NULL
)

INSERT INTO countriesHumanFacts (capitalCity, largestCity, populationInMillions, areaInThousandSquareMiles, drivingSide, languages, timeZone)
VALUES
('Algiers', null, 46, 920, 'Right', 'Arabic, Berber, French', 'UTC+1'),
('Luanda', null, 37, 481, 'Right', 'Portuguese, Umbundu', 'UTC+1'),
('Porto-Novo', 'Cotonou', 14, 43, 'Right', 'French, Fon, Yoruba', 'UTC+1'),
('Gaborone', null, 2.7, 225, 'Left', 'English, Setswana', 'UTC+2'),
('Ouagadougou', null, 23, 106, 'Right', 'French, Mooré, Dyula, Fula', 'UTC+0'),
('Gitega', 'Bujumbura', 13, 11, 'Right', 'Kirundi, French, English, Kiswahili', 'UTC+2'),
('Praia', null, 0.6, 1.6, 'Right', 'Portuguese, Kabuverdianu', 'UTC-1'),
('Yaoundé', null, 29, 184, 'Right', 'French, English', 'UTC+1'),
('Bangui', null, 5.7, 241, 'Right', 'French, Sangho, Banda, Gbaya', 'UTC+1'),
('N''Djamena', null, 18, 496, 'Right', 'French, Arabic, Sara', 'UTC+1'),
('Moroni', null, 0.9, 0.9, 'Right', 'Comorian, Arabic, French', 'UTC+3'),
('Brazzaville', null, 6.1, 132, 'Right', 'French, Lingala, Kituba(Kikongo)', 'UTC+1'),
('Kinshasa', null, 102, 906, 'Right', 'French, Lingala, Kikongo, Kiswahili, Tshiluba', ['UTC+1', 'UTC+2']),
('Yamoussoukro', 'Abidjan', 29, 125, 'Right', 'French, Dioula', 'UTC+0'),
('Djibouti City', null, 1.1, 9, 'Right', 'French, Arabic, Somali, Afar', 'UTC+3'),
('Cairo', null, 113, 387, 'Right', 'Arabic, English', 'UTC+2'),
('Malabo', 'Bata', 1.7, 11, 'Right', 'Spanish, French, Portuguese, Fang, Bubi', 'UTC+1'),
('Asmara', null, 3.7, 45, 'Right', 'Tigrinya, Arabic, English, Italian', 'UTC+3'),
('Mbabane', 'Manzini', 1.2, 7, 'Left', 'English, Swazi', 'UTC+2'),
('Addis Ababa', null, 127, 426, 'Right', 'Amharic, Oromo, Tigrinya, Somali, English', 'UTC+3'),
('Libreville', null, 2.4, 103, 'Right', 'French, Fang, Myene, Nzebi', 'UTC+1'),
('Accra', 'Kumasi', 34, 92, 'Right', 'English, pidgin English, Akan, Ewe, Fante', 'UTC+0'),
('Conakry', null, 14, 95, 'Right', 'French, Soussou, Fulani, Maninka', 'UTC+0'),
('Bissau', null, 2.2, 14, 'Right', 'Portuguese, Crioulo', 'UTC+0'),
('Nairobi', null, 57, 224, 'Left', 'English, Kiswahili', 'UTC+3'),
('Maseru', null, 2.3, 12, 'Left', 'English, Sesotho', 'UTC+2'),
('Monrovia', null, 5.4, 43, 'Right', 'English, pidgin English', 'UTC+0'),
('Tripoli', null, 7.1, 679, 'Right', 'Arabic, Italian, English', 'UTC+2'),
('Antananarivo', null, 29, 587, 'Right', 'Malagasy, French', 'UTC+3'),
('Lilongwe', null, 20, 46, 'Left', 'English, Chichewa', 'UTC+2'),
('Bamako', null, 23, 479, 'Right', 'French, Bambara, Arabic', 'UTC+0'),
('Nouakchott', null, 4.9, 398, 'Right', 'Arabic, Wolof, French', 'UTC+0'),
('Port Louis', null, 1.3, 0.8, 'Left', 'English, French, Creole, Hindi', 'UTC+4'),
('Rabat', 'Casablanca', 38, 274, 'Right', 'Arabic, French, Berber', 'UTC+1'),
('Maputo', null, 34, 309, 'Left', 'Portuguese', 'UTC+2'),
('Windhoek', null, 2.7, 319, 'Left', 'English, Afrikaans, German, Herero, Nama', 'UTC+2'),
('Niamey', null, 27, 489, 'Right', 'French, Hausa, Djerma', 'UTC+1'),
('Abuja', 'Lagos', 224, 357, 'Right', 'English, pidgin English, Hausa, Yoruba, Igbo', 'UTC+1'),
('Kigali', null, 14, 10, 'Right', 'Kinyarwanda, French, English, Kiswahili', 'UTC+2'),
('São Tomé', null, 0.2, 0.4, 'Right', 'Portuguese, Forro Creole', 'UTC+0'),
('Dakar', null, 18, 76, 'Right', 'French, Wolof, Pulaar, Jola, Mandinka', 'UTC+0'),
('Victoria', null, 0.1, 0.2, 'Left', 'English, French, Creole', 'UTC+4'),
('Freetown', null, 8.8, 28, 'Right', 'English, pidgin English, Mende, Temne', 'UTC+0'),
('Mogadishu', null, 18, 246, 'Right', 'Somali, Arabic, English, Italian', 'UTC+3'),
('Pretoria', 'Johannesburg', 61, 471, 'Left', 'English, Afrikaans, Zulu, Xhosa, Setswana', 'UTC+2'),
('Juba', null, 12, 249, 'Right', 'English, Juba Arabic, Dinka, Nuer, Luo', 'UTC+3'),
('Khartoum', null, 48, 719, 'Right', 'Arabic, English, Beja, Nubian', 'UTC+2'),
('Dodoma', 'Dar es Salaam', 67, 365, 'Left', 'Kiswahili, English, Arabic', 'UTC+3'),
('Banjul', null, 2.8, 4, 'Right', 'English, Mandinka, Wolof, Fula', 'UTC+0'),
('Lomé', null, 9.1, 22, 'Right', 'French, Ewe, Mina', 'UTC+0');
('Tunis', null, 12, 63, 'Right', 'Arabic, French', 'UTC+1'),
('Kampala', null, 49, 93, 'Left', 'English, Luganda, Kiswahili', 'UTC+3'),
('Lusaka', null, 21, 291, 'Left', 'English, Bemba, Kaonda, Lozi, Lunda', 'UTC+2'),
('Harare', null, 17, 151, 'Left', 'English, Chishona, Ndebele', 'UTC+2');